### ISSUE TITLE
Adopt Bun

### ISSUE THREAD

**Issue by IgorKrupenja** [IgorKrupenja/blog#51]
- [x] spyOn broken, actual method is called. likely https://github.com/oven-sh/bun/issues/6677
- [x] Github actions
- [x] https://bun.sh/docs/api/file-io#reading-files-bun-file
- [x] build? + GH action
- [x] `bun test --watch` - How to run from npm script?
- [x] publish broke with `Bun.file?`
- [x] `.toHaveBeenCalledWith` [will need](https://github.com/oven-sh/bun/issues/4365) a temp workaround
- [x] Running `bun test --watch` from npm script ignores `.env.test`
- [x] expect.objectContaining is not supported either
- [x] 1.0.8 canary: https://github.com/oven-sh/bun/issues/6831
- [x] `publishArticle` test failure, why? test examples https://github.com/oven-sh/bun/blob/3912f4d06418e1a8d430638fa7107ded3b601201/test/js/bun/test/mock/mock-module.test.ts
- [x] expectToHaveBeenCalledWith helper 2nd arg type should be `...unknown[]`
- [x] Can I use mock once w/o `mocke.restore`?
- [x] uploadImage, use Bun.file instead of fs.readfilesync
- [x] TS reports `mock.module` as undefined. Types not yet updated? Remove ignore comments in code
- [x] https://github.com/oven-sh/bun/issues/1546 maybe?
- [x] GH actions failing since 1.0.8 is not yet published
- [x] `expectToHaveBeenCalledWith` util does not respect arg order?
- [x] `publishArticle` strange behaviour of mock.module? https://discord.com/channels/876711213126520882/1169362490098979017 Also related? https://github.com/oven-sh/bun/issues/6874
- [x] `void` use with `mock.module`?
- [x] Replace custom `expectToHaveBeenCalledWith` with Bun's built-in. Remove chalk
- [x] Unable to resolve path to module 'bun:test' coming from `eslint-plugin-import` — need to report a bug there.

## Reported/existing issues

- https://github.com/oven-sh/bun/issues/4365
- https://github.com/oven-sh/bun/issues/6831
- https://github.com/oven-sh/bun/issues/6334
- https://github.com/oven-sh/bun/issues/8794

**Comment by Jarred-Sumner** [comment]
nice

@IgorKrupenja re: `spyOn`, if it was a module namespace object (`import * as Foo from 'bar';`), that will be fixed in the next release

**Comment by IgorKrupenja** [comment]
And I was about to go searching your repo and check if I need to report this 😅 Thank you for the pointer!

This was indeed the case, I tried it now with latest canary build and this is fixed.
